### ISSUE TITLE
hydra-link-checker blocked by CodePen (HTTP 403)

### ISSUE THREAD

**Issue by Krinkle** [jquery/infrastructure-puppet#75]
Since 31 January, CodePen seems to block all HTTP `HEAD` requests from [hydra-link-checker](https://github.com/jquery/hydra-link-checker/) in CI jobs such as https://github.com/qunitjs/qunit/actions/workflows/spider-check.yaml and https://github.com/jquery/api.jquery.com/actions/workflows/spider-check.yaml

```yaml
---
title: Broken Link Report
checked: 1579
number of email links: 0
emails: 
broken: 5
---

- code:    403
  url:     https://codepen.io/Krinkle/full/gbYdVRr
  parent:  https://qunitjs.com/blog/2022/04/16/redesign-module-selector/
  error:   Forbidden

- code:    403
  url:     https://codepen.io/Krinkle/full/mybzddj
  parent:  https://qunitjs.com/blog/2016/04/21/introduce-multi-select-module-picker/
  error:   Forbidden

…
```

**Workaround**: I've configured hydra to skip this domain for now, in https://github.com/qunitjs/qunit/commit/3ef1eb4868cf0fe0ff6951d441d2d7ecf350b239
